dbconvert/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', home.as_view()),
    path('1', home1),
    ]

sortimento/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teste/', include('dbconvert.urls')),
    url(r'^select2/', include('django_select2.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dbconvert/models.py
from django.db import models

# Create your models here.

class Sortemp(models.Model):
    id = models.AutoField(primary_key=True)
    Cod_sortimento = models.CharField(max_length=255, blank=True, null=True)
    Cod_secao = models.CharField(max_length=255, blank=True, null=True)
    Desc_secao = models.CharField(max_length=255, blank=True, null=True)
    Cod_tamanho = models.CharField(max_length=255, blank=True, null=True)
    Desc_tamanho = models.CharField(max_length=255, blank=True, null=True)
    Cod_publico = models.CharField(max_length=255, blank=True, null=True)
    Desc_publico = models.CharField(max_length=255, blank=True, null=True)
    Cod_mercadoria = models.CharField(max_length=255, blank=True, null=True)
    Desc_mercadoria = models.CharField(max_length=255, blank=True, null=True)
    Merc_conj = models.CharField(max_length=255, blank=True, null=True)
    Prioridade = models.CharField(max_length=255, blank=True, null=True)
    Qtde = models.CharField(max_length=255, blank=True, null=True)
    Voltagem = models.CharField(max_length=255, blank=True, null=True)
    Vigencia_inicio = models.DateField(blank=True, null=True)
    Vigencia_fim = models.DateField(blank=True, null=True)
    Status = models.CharField(max_length=2, blank=True, null=True)
    Setor = models.CharField(max_length=255, blank=True, null=True)
    Desc_setor = models.CharField(max_length=255, blank=True, null=True)
    Classe = models.CharField(max_length=255, blank=True, null=True)
    Desc_classe = models.CharField(max_length=255, blank=True, null=True)
    Especie = models.CharField(max_length=255, blank=True, null=True)
    Desc_especie = models.CharField(max_length=255, blank=True, null=True)
    Marca = models.CharField(max_length=255, blank=True, null=True)
    Desc_marca = models.CharField(max_length=255, blank=True, null=True)


class Sortim(models.Model):
    id = models.AutoField(primary_key=True)
    Empresa = models.CharField(max_length=255, blank=True, null=True)
    Filial = models.CharField(max_length=255, blank=True, null=True)
    Voltagem = models.CharField(max_length=255, blank=True, null=True)
    Cod_Publico = models.CharField(max_length=255, blank=True, null=True)
    Desc_Publico = models.CharField(max_length=255, blank=True, null=True)
    Cod_Secao = models.CharField(max_length=255, blank=True, null=True)
    Desc_Secao = models.CharField(max_length=255, blank=True, null=True)
    Cod_Sortimento = models.CharField(max_length=255, blank=True, null=True)
    Cod_Tamanho = models.CharField(max_length=255, blank=True, null=True)
    Desc_Tamanho = models.CharField(max_length=255, blank=True, null=True)
    Tipo_Publico = models.CharField(max_length=255, blank=True, null=True)
    Solic_Volt_Dif = models.CharField(max_length=255, blank=True, null=True)


class Cruzada(models.Model):
    id = models.IntegerField(primary_key=True)
    Cod_sortimento = models.CharField(max_length=255, blank=True, null=True)
    Cod_mercadoria = models.CharField(max_length=255, blank=True, null=True)
    Desc_mercadoria = models.CharField(max_length=255, blank=True, null=True)
    Prioridade = models.CharField(max_length=255, blank=True, null=True)
    Voltagem_item = models.CharField(max_length=255, blank=True, null=True)
    Voltagem_filial = models.CharField(max_length=255, blank=True, null=True)
    Vigencia_inicio = models.DateField(blank=True, null=True)
    Vigencia_fim = models.DateField(blank=True, null=True)
    Status = models.CharField(max_length=2, blank=True, null=True)
    Filial = models.IntegerField(blank=True, null=True)
    Cod_Secao = models.IntegerField(blank=True, null=True)
    Desc_Secao = models.CharField(max_length=255, blank=True, null=True)
    Cod_Tamanho = models.CharField(max_length=255, blank=True, null=True)
    Desc_Tamanho = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = "cruzada"


class Tamanhos(models.Model):
    Tamanho = models.CharField(max_length=20)
    Tipo = models.CharField(max_length=20)


class Perfil(models.Model):
    Nome = models.CharField(max_length=100)
    Tamanho = models.ForeignKey(Tamanhos, on_delete=models.CASCADE)


class Secao(models.Model):
    Cod_secao = models.IntegerField(primary_key=True)
    Descricao = models.CharField(max_length=255)


class Classificacao(models.Model):
    cod_secao = models.ForeignKey(Secao, on_delete=models.CASCADE)
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    Quantidade = models.IntegerField()

dbconvert/views.py
from datetime import datetime
from django.db import connection
import pandas as pd
from django.forms import model_to_dict
from django.http import HttpResponse, request, HttpResponseForbidden
from django.shortcuts import render
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin
from .filters import CruzadaFilter
from .process_csv_sort import *
from .models import *
from .tables import TabelaCruzada


query = '''Select
    dbconvert_sortemp.Cod_mercadoria,
    dbconvert_sortemp.Desc_mercadoria,
    dbconvert_sortemp.Prioridade,
    dbconvert_sortemp.Qtde,
    dbconvert_sortemp.Voltagem,
    dbconvert_sortemp.Vigencia_inicio,
    dbconvert_sortemp.Vigencia_fim,
    dbconvert_sortemp.Status
From
    dbconvert_sortim Left Join
    dbconvert_sortemp On dbconvert_sortim.Cod_Sortimento = dbconvert_sortemp.Cod_sortimento And
            dbconvert_sortim.Cod_Secao = dbconvert_sortemp.Cod_secao
Where
    dbconvert_sortim.Filial = '1000' And
    dbconvert_sortim.Cod_Secao = '16'
Group By
    dbconvert_sortim.Filial,
    dbconvert_sortim.Cod_Secao,
    dbconvert_sortemp.Cod_mercadoria,
    dbconvert_sortemp.Desc_mercadoria,
    dbconvert_sortemp.Prioridade,
    dbconvert_sortemp.Qtde,
    dbconvert_sortemp.Voltagem,
    dbconvert_sortemp.Vigencia_inicio,
    dbconvert_sortemp.Vigencia_fim,
    dbconvert_sortemp.Status,
    dbconvert_sortemp.Desc_tamanho,
    dbconvert_sortemp.Cod_tamanho'''


def home1(request):
    a = csv_pandas()
    # row = [
    #     ((d) for d in Sortim.objects.all().values_list('Cod_Secao', 'Desc_Secao').distinct())
    # ]
    #
    # for i in row:
    #     for j in i:
    #         print(j, 'opa')
    #
    # now = datetime.now()


    return render(request,'listas.html', {'now': a})

class home(SingleTableMixin, FilterView):
    table_class = TabelaCruzada
    model = Cruzada
    template_name = "lista.html"
    filterset_class = CruzadaFilter

dbconvert/templates/lista.html
<html>
{% load django_tables2 %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{{ form.media.css }}


<head>
    <title>List of persons</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.jquery.min.js"></script>
{#    <link href="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.min.css" rel="stylesheet"/>#}
    <link href="{% static "choice.css" %}" rel="stylesheet"/>
</head>
<style>

    .table td, .table th {
        font-size: small;
    }
    .chosen-container-single .chosen-single {
    position: relative;
    display: block;
    overflow: hidden;
    padding: 0 0 0 8px;
    height: 31px;
    border: 1px solid #aaa;
    border-radius: 0px;
    background-color: #fff;
    background: -webkit-gradient(linear,left top,left bottom,color-stop(20%,#fff),color-stop(50%,#f6f6f6),color-stop(52%,#eee),to(#f4f4f4));
    background: linear-gradient(#fff 20%,#f6f6f6 50%,#eee 52%,#f4f4f4 100%);
    background-clip: padding-box;
    -webkit-box-shadow: 0 0 3px #fff inset, 0 1px 1px rgba(0,0,0,.1);
    box-shadow: 0 0 3px #fff inset, 0 1px 1px rgba(0,0,0,.1);
    color: #444;
    text-decoration: none;
    white-space: nowrap;
    line-height: 24px;
    }
    .orderable {
        cursor: pointer;
    }
    .orderable {
        cursor: pointer;
    }
    span{
        height: 31px;
    }
    .butn:after {
        font-family: FontAwesome;
        content: "\f0dc";
        color: grey
    }
    .descen:after {
        font-family: FontAwesome;
        content: "\f0de";
        color: black;
        text-align: justify;
        text-justify: inter-word;
    }
    .ascend:after {
        font-family: FontAwesome;
        content: "\f0dd";
        color: black;
        text-align: justify;
        text-justify: inter-word;
    }
    a:not([href]):not([tabindex]) {
        color: black;!important;
        text-decoration: none;
    }
    .page-link {
    position: relative;
    display: block;
    padding: .5rem .75rem;
    margin-left: -1px;
    line-height: 1.25;
    color: #2e8b57;
    background-color: #fff;
    border: 1px solid #dee2e6;
}
    .page-item.active .page-link {
        z-index: 1;
        color: #fff;
        background-color: #2e8b57;
        border-color: #2e8b57;
    }

</style>

<body>


{% block table %}
<div class="border rounded border-success" style="margin: 10px;">
    <div class="row" style="margin: 0;">
        <div class="col text-center" style="background-color: #2e8b57;min-height: 40px;padding-top: 8px;"><span class="text-white" style="font-weight: bold;">CONSULTA DE SORTIMENTO LOJA</span></div>
    </div>
    <form method="get">
    <div class="row" style="margin: 0;margin-top: 10px;margin-bottom: 10px;">
        <div class="col-2 d-inline-flex justify-content-between" style="padding-right: 0;">
            <div class="input-group input-group-sm" style="height:10px">
                <div class="input-group-prepend"><span class="input-group-text">Filial</span></div><input type="number" name="Filial" class="form-control" autocomplete="off" placeholder="Filial" id="id_Filial" value="{{ filter.form.Filial.value }}"/>
                <div class="input-group-append"></div>
            </div>
        </div>
        <div class="col-6">
            <div class="input-group input-group-sm">
                <div class="input-group-prepend"><span class="input-group-text">Seção</span></div><select class="form-control-sm chosen-select" name='Cod_Secao' style="width: 75%;height: 31px;" required> {% for i in filter.form.Cod_Secao %}{{ i }}{% endfor %} </select>
                <div class="input-group-append"><button class="btn" type="submit" style="background: #2E8B57;color: white">Buscar</button></div>
            </div>
        </div>
        <div class="col-4">
            <div class="input-group input-group-sm">
                <div class="input-group-prepend" ><span class="input-group-text">Tamanho</span></div><input type="text" class="form-control" autocomplete="off" readonly value="{% for row in table.paginated_rows|slice:"0:1" %}{% for column, cell in row.items %}{% if column|slugify == 'cod-tamanho' %}{{ cell|cut:" " }} - {% endif %}{% if column|slugify == 'desc-tamanho' %}{{ cell|cut:" " }}{% endif %}{% endfor %}{% endfor %}"/>
                <div class="input-group-append"></div>
            </div>
        </div>
    </div>
    </form>
    <div class="row" style="margin: 0;">
        <div class="col">
            <div class="table-responsive table-bordered border rounded border-success" style="margin-bottom: 10px;">
                <table class="table table-striped table-bordered table-sm">
                    {% block table.thead %}
                    {% if table.show_header %}
                    <thead {{ table.attrs.thead.as_html }}>
                    <tr class="table" style="background: #98FB98 ">
                        {% for column in table.columns %}
                            {% if column.header|slugify == 'cod-tamanho' or column.header|slugify == 'desc-tamanho' %}
                            {% else %}
                        <th {{ column.attrs.th.as_html }}>
                            {% if column.orderable %}
                            <a style='width:100%;border:0;color: #222222' class="d-inline-flex justify-content-between btn butn {% if column.order_by_alias.next|slice:':1' == '-' %}ascend{% elif column.order_by_alias.next|capfirst in request.get_full_path %}descen{% else %} {% endif %}" href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}&nbsp; </a>
                            {% else %}
                            {{ column.header }}
                            {% endif %}
                        </th>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    </thead>
                    {% endif %}
                    {% endblock table.thead %}
                    {% block table.tbody %}
                    <tbody {{ table.attrs.tbody.as_html }}>
                    {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                            {% if column.header|slugify == 'cod-tamanho' or column.header|slugify == 'desc-tamanho' %}
                            {% else %}
                        <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                    {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                    <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                    {% endfor %}
                    </tbody>
                    {% endblock table.tbody %}
                    {% block table.tfoot %}
                    {% if table.has_footer %}
                    <tfoot {{ table.attrs.tfoot.as_html }}>
                    <tr>
                        {% for column in table.columns %}
                        <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                        {% endfor %}
                    </tr>
                    </tfoot>
                    {% endif %}
                    {% endblock table.tfoot %}
                </table>
                {% endblock table %}
            </div>
        </div>
    </div>
</div>



<hr>
{% block table-wrapper %}
{% block pagination %}
{% if table.page and table.paginator.num_pages > 1 %}
<nav aria-label="Table navigation">
    <ul class="pagination justify-content-center">
        {% if table.page.has_previous %}
        {% block pagination.previous %}
        <li class="previous page-item">
            <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="page-link">
                <span aria-hidden="true">&laquo;</span>
                {% trans 'previous' %}
            </a>
        </li>
        {% endblock pagination.previous %}
        {% endif %}
        {% if table.page.has_previous or table.page.has_next %}
        {% block pagination.range %}
        {% for p in table.page|table_page_range:table.paginator %}
        <li class="page-item{% if table.page.number == p %} active{% endif %}">
            <a class="page-link" {% if p != '...' %}href="{% querystring table.prefixed_page_field=p %}"{% endif %}>
                {{ p }}
            </a>
        </li>
        {% endfor %}
        {% endblock pagination.range %}
        {% endif %}
        {% if table.page.has_next %}
        {% block pagination.next %}
        <li class="next page-item">
            <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="page-link">
                {% trans 'next' %}
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endblock pagination.next %}
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock pagination %}
{% endblock table-wrapper %}
</div>
{{ form.media.js }}
</body>
<script>
$(".chosen-select").chosen({
  no_results_text: "Oops, nothing found!"
})
</script>
</html>

dbconvert/templates/listas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>Agora é {{ now }}<br>
<hr>
Filial 1000 - Seção 6
<hr>
{% for data in row %}
    {{ data }}
{% endfor %}
<br>
</body>
</html>